# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EamCollector < Formula
  desc "AI usage collector agent for Enterprise Agent Management"
  homepage "https://github.com/AutobahnSecurity/eam-collector"
  version "0.3.2"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v0.3.2/eam-collector-0.3.2-darwin-amd64.tar.gz"
      sha256 "133bb5500dd7e6fda84e8b8dba76fca6cef8059256ce119d33ebd3a637e7435f"

      define_method(:install) do
        bin.install "eam-collector"
        (etc/"eam-collector").mkpath
        etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v0.3.2/eam-collector-0.3.2-darwin-arm64.tar.gz"
      sha256 "12b3b55ed5201b4be6b227c7010800f4f99487f412225bc72c2b679e7c4febeb"

      define_method(:install) do
        bin.install "eam-collector"
        (etc/"eam-collector").mkpath
        etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v0.3.2/eam-collector-0.3.2-linux-amd64.tar.gz"
      sha256 "254c7c3a765128c8a953259e17526ad54d04ff012846d78ab9102043f41df1a5"
      define_method(:install) do
        bin.install "eam-collector"
        (etc/"eam-collector").mkpath
        etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v0.3.2/eam-collector-0.3.2-linux-arm64.tar.gz"
      sha256 "c29b79e890dba81e7eddcb8e4f05d18470017d66c8e25be680e3ec3c284e8b9d"
      define_method(:install) do
        bin.install "eam-collector"
        (etc/"eam-collector").mkpath
        etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
      end
    end
  end

  def post_install
    config_dir = Pathname.new("#{Dir.home}/.eam-collector")
    config_dir.mkpath
    config_file = config_dir/"config.yaml"
    unless config_file.exist?
      cp etc/"eam-collector/config.example.yaml", config_file
      ohai "Config template created at #{config_file}"
      ohai "Edit it with your server URL and API key before starting the service"
    end
  end

  def caveats
    <<~EOS
      To get started:

        1. Edit your config with your EAM server URL and API key:
           nano ~/.eam-collector/config.yaml

        2. Start the background daemon:
           brew services start eam-collector

        3. Check logs:
           tail -f #{var}/log/eam-collector.log
    EOS
  end

  service do
    run [opt_bin/"eam-collector"]
    keep_alive true
    log_path var/"log/eam-collector.log"
    error_log_path var/"log/eam-collector.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/eam-collector --version")
  end
end
