# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EamCollector < Formula
  desc "AI usage collector agent for Enterprise Agent Management"
  homepage "https://github.com/AutobahnSecurity/eam-collector"
  version "0.6.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v0.6.0/eam-collector-0.6.0-darwin-amd64.tar.gz"
      sha256 "4b4b066e8e76e1765d7a2273dc2072e30a010316046ceb67ce67f038fd74076a"

      define_method(:install) do
        bin.install "eam-collector"
        (etc/"eam-collector").mkpath
        etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v0.6.0/eam-collector-0.6.0-darwin-arm64.tar.gz"
      sha256 "0f327ed7e4f52974f2ff0e06b6e3adfcab11126f99c4abc8a8f231ddbdcf1acd"

      define_method(:install) do
        bin.install "eam-collector"
        (etc/"eam-collector").mkpath
        etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v0.6.0/eam-collector-0.6.0-linux-amd64.tar.gz"
      sha256 "bcc40a3d81a178d1db824fc8b57d76709e6e9e12fe649bfc49b86679ba6d127c"
      define_method(:install) do
        bin.install "eam-collector"
        (etc/"eam-collector").mkpath
        etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v0.6.0/eam-collector-0.6.0-linux-arm64.tar.gz"
      sha256 "c8a0e7a25a500c3dd0f7a3ad95cf5f77dacb51970dceb0a04e0e9471e600ab0e"
      define_method(:install) do
        bin.install "eam-collector"
        (etc/"eam-collector").mkpath
        etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
      end
    end
  end

  def post_install
    config_dir = Pathname.new("#{Dir.home}/.eam-collector")
    config_dir.mkpath
    config_file = config_dir/"config.yaml"
    unless config_file.exist?
      cp etc/"eam-collector/config.example.yaml", config_file
      ohai "Config template created at #{config_file}"
      ohai "Edit it with your server URL and API key before starting the service"
    end
  end

  def caveats
    <<~EOS
      To get started:

        1. Edit your config with your EAM server URL and API key:
           nano ~/.eam-collector/config.yaml

        2. Start the background daemon:
           brew services start eam-collector

        3. Check logs:
           tail -f #{var}/log/eam-collector.log
    EOS
  end

  service do
    run [opt_bin/"eam-collector"]
    keep_alive true
    log_path var/"log/eam-collector.log"
    error_log_path var/"log/eam-collector.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/eam-collector --version")
  end
end
